// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD62PPH9FhWiiwI9bCqtjf9VngzML7BcB0',
    appId: '1:321564462213:web:9be513bd5db29940b62dec',
    messagingSenderId: '321564462213',
    projectId: 'fir-auth-demo-dd337',
    authDomain: 'fir-auth-demo-dd337.firebaseapp.com',
    storageBucket: 'fir-auth-demo-dd337.firebasestorage.app',
    measurementId: 'G-CMKPLF1VRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbjGQw8tO91VCB38uqdqbv27-RPZRVs8',
    appId: '1:321564462213:android:6f2bd368500afc6fb62dec',
    messagingSenderId: '321564462213',
    projectId: 'fir-auth-demo-dd337',
    storageBucket: 'fir-auth-demo-dd337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwv03HkAVEGbmCCGMZVUHniV8-YFZkZ1I',
    appId: '1:321564462213:ios:a24b759edc6e2f80b62dec',
    messagingSenderId: '321564462213',
    projectId: 'fir-auth-demo-dd337',
    storageBucket: 'fir-auth-demo-dd337.firebasestorage.app',
    iosClientId: '321564462213-8ln9m49p5dmccb75d3qe400ffsp55hcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwv03HkAVEGbmCCGMZVUHniV8-YFZkZ1I',
    appId: '1:321564462213:ios:a24b759edc6e2f80b62dec',
    messagingSenderId: '321564462213',
    projectId: 'fir-auth-demo-dd337',
    storageBucket: 'fir-auth-demo-dd337.firebasestorage.app',
    iosClientId: '321564462213-8ln9m49p5dmccb75d3qe400ffsp55hcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD62PPH9FhWiiwI9bCqtjf9VngzML7BcB0',
    appId: '1:321564462213:web:3b358dc54760cfe1b62dec',
    messagingSenderId: '321564462213',
    projectId: 'fir-auth-demo-dd337',
    authDomain: 'fir-auth-demo-dd337.firebaseapp.com',
    storageBucket: 'fir-auth-demo-dd337.firebasestorage.app',
    measurementId: 'G-ZE47TF3LEL',
  );

}